version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  configserver:
    environment:
      - spring.cloud.config.server.git.uri=https://github.com/SteeltoeOSS/eShopOnContainers-config.git
    ports:
      - "8888:8888"

  eurekaserver:
    ports:
      - "8761:8761"

  sql.data:
    environment:
      - MYSQL_ROOT_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "3306:3306"    # Important: In a production environment your should remove the external port

  nosql.data:
    ports:
      - "27017:27017"  # Important: In a production environment your should remove the external port

  basket.data:
    ports:
      - "6379:6379"    # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5105:80"   

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5103:80"   # Important: In a production environment your should remove the external port (5103) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80). 

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5101:80"   # Important: In a production environment your should remove the external port (5101) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5102:80"   # Important: In a production environment your should remove the external port (5102) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  ordering.backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5111:80"

  marketing.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5110:80"   # Important: In a production environment your should remove the external port (5110) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5108:80"   # Important: In a production environment your should remove the external port (5108) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  locations.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5109:80"   # Important: In a production environment your should remove the external port (5109) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  mobileshoppingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - eureka__client__serviceUrl=http://eurekaserver:8761/eureka/
      - spring__application__name=mobileshoppingapigw
      - externalUrl=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5200
    ports:
      - "5200:80"   
    volumes:
      - ./src/ApiGateways/Mobile.Bff.Shopping/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}

  mobilemarketingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - eureka__client__serviceUrl=http://eurekaserver:8761/eureka/
      - spring__application__name=mobilemarketingapigw
      - externalUrl=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5201
    ports:
      - "5201:80"   
    volumes:
      - ./src/ApiGateways/Mobile.Bff.Marketing/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}

  webshoppingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - eureka__client__serviceUrl=http://eurekaserver:8761/eureka/
      - spring__application__name=webshoppingapigw
      - externalUrl=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
    ports:
      - "5202:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Shopping/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}

  webmarketingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - eureka__client__serviceUrl=http://eurekaserver:8761/eureka/
      - spring__application__name=webmarketingapigw
      - externalUrl=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5203
    ports:
      - "5203:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Marketing/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}

  mobileshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__identity=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - eureka__client__serviceUrl=http://eurekaserver:8761/eureka/
    ports:
      - "5120:80"   # Important: In a production environment your should remove the external port (5120) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__identity=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - eureka__client__serviceUrl=http://eurekaserver:8761/eureka/
    ports:
      - "5121:80"   # Important: In a production environment your should remove the external port (5121) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).

  ordering.signalrhub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5112:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5107:80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5104:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ESHOP_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}
      - ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5100:80"
